### ISSUE TITLE
post要加一下delete link

### ISSUE THREAD

**Issue by zhujinlong** [agilejzl/blog-eye#13]
<del>post要加一下delete link哈，不然文章删不了；
另外，</del> 我用chrome的extension Postman给http://www.blog-eye.com/posts/21 发了一个delete请求，但是返回的是404，这是何故？Postman发请求应该已经附带了chrome所保存的blog-eye.com的cookie了.

**Comment by agilejzl** [comment]
这种最基本的功能肯定有的，请你 rake routes | grep post 看看，post的路由有三个namespace，分别是frontend、admin、system，/posts/:id 是查看post的，/admin/posts/:id 才能管理post。

**Comment by zhujinlong** [comment]
恩，后来发现了，所以把那半句加了<del>哈
